title: Marijn Stapert
permalink: /blog/:title/:year/:month/:day/

github: https://github.com/MFStapert
linkedin: https://www.linkedin.com/in/marijn-stapert-05091182/
twitter: https://twitter.com/MarijnStapert

sass:
  style: compressed
  sass_dir: _sass
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
